### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by JustinB77** [MarioMakingMods/FSTM-CSTM-FSTP-Converter#3]
This is more of a "Me not knowing python" situation rather than an issue. I've tried to figure out how this program works but nothing ever happens. It just sends me to the usage screen every time. Commands such as "main.py -format FWAV -bom 1 name.bfstm" is just one thing I've tried (without the quotes). Please if someone could help, i would be forever in your debt. (I've been at this for too long so anything you've got would a be a nice help.)

**Comment by aboood40091** [comment]
Try adding "python" to the command before "main.py"

**Comment by JustinB77** [comment]
Wow thank you! Again, I'm not the best with python so I have no clue why you would have to put that first since the one file name is main.py (.py being python i assume) soooo yea. But Thank you!
