### ISSUE TITLE
It just launches the startup text?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [MarioMakingMods/FSTM-CSTM-FSTP-Converter#4]
When I launch main.py with command line with parameters all it does is just launch the startup text. Then it closes. GARBAGE

**Comment by umustbeloggedintododat** [comment]
NVM it was just my dumb brain.

**Comment by aboood40091** [comment]
> GARBAGE
> NVM it was just my dumb brain.

Way to embarrass yourself there.
