### ISSUE TITLE
Converter complains about super()

### ISSUE THREAD

**Issue by maxtron95** [MarioMakingMods/FSTM-CSTM-FSTP-Converter#5]
Hello, I am trying to convert a bcstm file into a bcwav file for sounds to use in the Usagi 3DS Theme Editor, but when I try to run this command on Linux:

`python main.py -format CWAV -bom 1 '/home/creepertron/Utilities/BCFSTM-BCFWAV-Converter/ScreenSelectStyle change.bcstm'`

I get this output:

`BCFSTM-BCFWAV Converter v2.1
(C) 2017-2018 AboodXD
Traceback (most recent call last):
  File "main.py", line 847, in <module>
    if __name__ == '__main__': main()
  File "main.py", line 837, in main
    outputBuffer = convFile(inb, dest, dest_bom)
  File "main.py", line 48, in convFile
    outputBuffer = STMtoWAV(f, magic, dest, dest_bom)
  File "main.py", line 535, in STMtoWAV
    header = Header(bom)
  File "/home/creepertron/Utilities/BCFSTM-BCFWAV-Converter/structs.py", line 28, in __init__
    super().__init__(bom + '4s2xH2I2H')
TypeError: super() takes at least 1 argument (0 given)`

I'm not sure what I'm doing wrong or if I typed it incorrectly.

**Comment by aboood40091** [comment]
Hello. What version of python are you using?

**Comment by maxtron95** [comment]
python version output reads `Python 2.7.16`, I figured out what I was doing wrong when you asked that question, I had to use the `python3` command instead of `python` and it worked. I don't know why my linux setup used Python 2 instead of Python 3 when typing `python`. Sorry to bother you.

**Comment by aboood40091** [comment]
Hoping the converted output works. :)

**Comment by maxtron95** [comment]
@aboood40091 The output works, I was able to import the converted files into the 3DS theme editor and use it on my homebrewed DS to create a DDR-style custom theme. Thank you for making the tool that allows me to convert to BCWAV files.

https://user-images.githubusercontent.com/53346722/105543772-c9423380-5cbf-11eb-979e-e423ce22a75d.mp4
